import { NgModule } from '@angular/core';
import { CommonModule, } from '@angular/common';
//import { BrowserModule  } from '@angular/platform-browser';
import { Routes, RouterModule } from '@angular/router';
import { ModuleWithProviders } from '@angular/core';
import {HomeTutorComponent} from './home-tutor.component';
import {HomeTutorInBangaloreComponent} from './home-tutor-in-bangalore/home-tutor-in-bangalore.component';
import { CommonTemplateComponent } from './common-template/common-template.component';

const routes: Routes =[
    {path: '',
    component: HomeTutorComponent,
    children: [
    { path: 'common-template', component: CommonTemplateComponent}, 
    
    //Subject Routing
    { path: 'home-tutor-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'maths-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'science-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'english-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'physics-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'social-science-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'hindi-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'chemistry-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'biology-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'accounting-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'history-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'geography-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },

    //State Board/CBSC/ICSC Board Routing
    { path: 'cbse-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'icse-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'state-board-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'igcse-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    { path: 'karanaka-board-home-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    
    //Grade Or class Routing
    {path: 'nursery-kg-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-6-7-8-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-1-2-3-4-5-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-9-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-10-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-11-science-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-11-commerce-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-11-arts-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-12-science-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-12-arts-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },
    {path: 'class-12-commerce-home-tuition-tutors-in-bangalore', component: HomeTutorInBangaloreComponent },

    //Area Or Location Based Routing
    {path: 'a-f-station-yelahanka-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'adugodi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'agara-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'agram-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'air-force-hospital-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'amruthahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'anandnagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'anekal-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'anekalbazar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'arabic-college-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'aranya-bhavan-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'ashoknagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'attibele-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'attur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'austin-town-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'avalahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'avani-sringeri-mutt-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'avenue-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'b-sk-ii-stage-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bsf-campus-yelahanka-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bagalgunte-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bagalur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'balepete-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'banashankari-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'banashankari-iii-stage-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'banaswadi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bandikodigehalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bangalore-air-port-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bangalore-bazaar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bangalore-city-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bangalore-corporation-building-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bangalore-dist-offices-bldg-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bangalore-fort-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bangalore-sub-fgn-post-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bangalore.-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bannerghatta-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bannerghatta-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bapujinagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'basavanagudi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'basavaraja-market-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'basaveshwaranagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'basaveswaranagar-ii-stage-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bellandur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'benson-town-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bestamaranahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bettahalsur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bhashyam-circle-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bhattarahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bidaraguppe-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bidrahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bnagalore-viswavidalaya-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'bommanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'brigade-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'byatarayanapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'c.v.raman-nagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'cmp-centre-and-school-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'crpf-campus-yelahanka-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'cahmrajendrapet-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'chamrajpet-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'chamrajpet-bazar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'chandra-lay-out-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'chickpet-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'chikkabettahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'chikkajala-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'chikkalasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'chikkanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'chunchanakuppe-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'cubban-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'dasarahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'deepanjalinagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'devanagundi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'devarjeevanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'devasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'dharmaram-college-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'doddagubbi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'doddajala-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'doddakallasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'doddanekkundi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'domlur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'dommasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'doorvaninagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'dr.-ambedkar-veedhi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'electronics-city-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'fraser-town-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'g.k.v.k.-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'gaviopuram-extension-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'gaviopuram-guttanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'gayathrinagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'girinagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'goraguntepalya-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'goripalya-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'governmemnt-electric-factory-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'govindapalya-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'gunjur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'h-m-t-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'h.a.-farm-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'h.a.l-ii-stage-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'h.k.p.-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hsr-layout-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hampinagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'handenahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'harogadde-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hebbal-kempapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hennagara-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'highcourt-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hongasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hoodi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'horamavu-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hosakerehalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hosur-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hulimangala-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hulimavu-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hulsur-bazaar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'hunasamaranahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'isro-anthariksha-bhavan-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'immedihalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'indalavadi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'indiranagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'indiranagar-com.-complex-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'industrial-estate-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'ittamadu-layout-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'j-p-nagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'j.c.nagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jakkur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jalahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jalahalli-east-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jalahalli-village-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jalahalli-west-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jalavayuvihar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jayanagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jayanagar-west-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jayangar-east-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jayangar-iii-block-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jeevanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jeevanbhimanagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jigani-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'jp-nagar-iii-phase-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'k-h-b-colony-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'k.-g.-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'k.p.west-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kacharakanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kadabagere-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kadugodi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kalkunte-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kalyanagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kamagondanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kamakshipalya-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kannamangala-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kannur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kanteeravanagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kathriguppe-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kenchanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kendriya-sadan-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kendriya-vihar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kodigehalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'konanakunte-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'koramangala-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'koramangala-i-block-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'koramangala-vi-bk-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kothanur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'krishnarajapuram-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'krishnarajapuram-r-s-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kugur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kumaraswamy-layout-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kumbalgodu-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'kundalahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'lalbagh-west-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'legislators-home-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'lingarajapuram-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'm-s-r-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'madhavan-park-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'madivala-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'magadi-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mahadevapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mahalakshmipuram-layout-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mahatma-gandhi-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'malkand-lines-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mallathahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'malleswaram-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'malleswaram-west-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mandalay-lines-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'marathahalli-colony-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'marsur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'maruthi-sevanagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mathikere-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mavalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mayasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'medihalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'medimallasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mico-layout-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'milk-colony-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mount-st-joseph-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'msrit-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'mundur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'museum-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'muthanallur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'muthusandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'nal-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'naduvathi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'nagarbhavi-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'nagasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'nagavara-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'nandinilayout-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'narasimharaja-colony-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'narasimjharaja-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'narayan-pillai-street-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'nayandahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'neralur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'new-tharaggupet-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'new-thippasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'okalipuram-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'p&t-col.-kavalbyrasandra-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'padmanabhnagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'palace-guttahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'panathur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'pasmpamahakavi-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'peenya-i-stage-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'peenya-ii-stage-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'peenya-small-industries-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'r-t-nagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'r.m.v.-extension-ii-stage-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'rajajinagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'rajajinagar-i-block-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'rajajinagar-ivth-block-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'rajanakunte-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'rajarajeshwarinagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'rajbhavan-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'ramachandrapuram-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'ramagondanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'ramakrishna-hegde-nagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'ramamurthy-nagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'rameshnagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'richmond-town-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'rv-niketan-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'sadashivanagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'sahakaranagar-p.o-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'samandur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'samethanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'sampangiramnagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'sarjapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'science-institute-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'seshadripuram-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'shankarpura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'shanthinagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'sidihoskote-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'singanayakanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'sivan-chetty-gardens-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'someswarapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'sri-jayachamarajendra-road-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'srirampuram-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'st.-johns-medical-college-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'st.-thomas-town-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'state-bank-of-mysore-colony-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'subhashnagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'subramanyapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'swimming-pool-extn-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'tarahunise-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'tavarekere-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'taverekere-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'thambuchetty-palya-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'thammanayakanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'tilaknagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'training-command-iaf-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'tyagrajnagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'ullalu-upanagara-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vanakanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vartur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vasanthnagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'venkatarangapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'venkateshapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vidhana-soudha-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vidyanagara-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vidyaranyapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vijayanagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vijayanagar-east-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vikramnagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vimapura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'virgonagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'visveswarapuram-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'viswaneedam-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vittalnagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'viveknagar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'vyalikaval-extn-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'wheel-and-axle-plant-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'whitefield-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'wilson-garden-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'yadavanahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'yediyur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'yelachenahalli-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'yelahanka-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'yelahanka-satellite-town-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'yemalur-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'yeshwanthpur-bazar-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'yeswanthpura-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'btm-layout-1st-stage-home-tuition-tutors', component: HomeTutorInBangaloreComponent },
    {path: 'btm-layout-2nd-stage-home-tuition-tutors', component: HomeTutorInBangaloreComponent },    



    { path: '', redirectTo: 'home-tutor-in-bangalore', pathMatch: 'full' },
    {path: '**', redirectTo: 'home-tutor-in-bangalore' }
 ] 
}
];

export const routing = RouterModule.forChild(routes);